### ISSUE TITLE
报错信息

### ISSUE THREAD

**Issue by liaoran** [cqcre/TaobaoMM#2]
```
[E 160417 20:21:37 base_handler:194] HTTP 599: Could not resolve host: https
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pyspider/libs/base_handler.py", line 187, in run_task
        result = self._run_task(task, response)
      File "/usr/local/lib/python2.7/dist-packages/pyspider/libs/base_handler.py", line 166, in _run_task
        response.raise_for_status()
      File "/usr/local/lib/python2.7/dist-packages/pyspider/libs/response.py", line 183, in raise_for_status
        raise http_error
    HTTPError: HTTP 599: Could not resolve host: https
```

这是什么情况呢，我把https改成http也是报这个错误

**Comment by Germey** [comment]
http://cuiqingcai.com/2703.html 看下这个
