### ISSUE TITLE
运行报错'Handler' object has no attribute 'deal'

### ISSUE THREAD

**Issue by lily7714** [cqcre/TaobaoMM#4]
[E 170510 16:20:24 base_handler:203] 'Handler' object has no attribute 'deal'
    Traceback (most recent call last):
      File "/Library/Python/2.7/site-packages/pyspider/libs/base_handler.py", line 196, in run_task
        result = self._run_task(task, response)
      File "/Library/Python/2.7/site-packages/pyspider/libs/base_handler.py", line 176, in _run_task
        return self._run_func(function, response, task)
      File "/Library/Python/2.7/site-packages/pyspider/libs/base_handler.py", line 155, in _run_func
        ret = function(*arguments[:len(args) - 1])
      File "<taobaomm>", line 44, in domain_page
    AttributeError: 'Handler' object has no attribute 'deal'

**Comment by Germey** [comment]
__init__那边不是初始化了吗？
